### ISSUE TITLE
Empty password in request passed to server

### ISSUE THREAD

**Issue by zaroth** [mtgred/netrunner#2085]
From the exception log, it looks like somewhere it's possible to send an empty password request (I'm not sure whether via login, registration or making/joining passworded games, the log comes from the test server which was used by many at the time) to server. Log comes from the coffee server.coffee process:

<pre>
TypeError: Cannot read property 'password' of undefined
  at Socket.<anonymous> (/opt/jinteki/netrunner/server.coffee:208:20)
  at emitTwo (events.js:106:13)
  at Socket.emit (events.js:191:7)
  at Socket.onevent (/opt/jinteki/netrunner/node_modules/socket.io/lib/socket.js:330:8)
  at Socket.onpacket (/opt/jinteki/netrunner/node_modules/socket.io/lib/socket.js:290:12)
  at Client.ondecoded (/opt/jinteki/netrunner/node_modules/socket.io/lib/client.js:193:14)
  at Decoder.Emitter.emit (/opt/jinteki/netrunner/node_modules/component-emitter/index.js:134:20)
  at Decoder.add (/opt/jinteki/netrunner/node_modules/socket.io-parser/index.js:247:12)
  at Client.ondata (/opt/jinteki/netrunner/node_modules/socket.io/lib/client.js:175:18)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at Socket.onPacket (/opt/jinteki/netrunner/node_modules/engine.io/lib/socket.js:99:14)
  at emitOne (events.js:96:13)
  at XHR.emit (events.js:188:7)
  at XHR.Transport.onPacket (/opt/jinteki/netrunner/node_modules/engine.io/lib/transport.js:91:8)
  at callback (/opt/jinteki/netrunner/node_modules/engine.io/lib/transports/polling.js:202:10)
  at Object.exports.decodePayload (/opt/jinteki/netrunner/node_modules/engine.io-parser/lib/index.js:320:19)
  at XHR.Polling.onData (/opt/jinteki/netrunner/node_modules/engine.io/lib/transports/polling.js:205:10)
  at IncomingMessage.onEnd (/opt/jinteki/netrunner/node_modules/engine.io/lib/transports/polling.js:158:10)
  at emitNone (events.js:86:13)
  at IncomingMessage.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:974:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)
</pre>

**Comment by domtancredi** [comment]
Given it's from a socket-based stacktrace, and involves password, I'm assuming something to do with this commit or line:
https://github.com/mtgred/netrunner/commit/b1ca75c3634c6c2b2c4a7e489dd13d6a0e0da059#diff-f704858f8ac261810bd942b45fd38e5d

Not sure how to reproduce

**Comment by domtancredi** [comment]
Issue is in this line of code:
`if not game.password or game.password.length is 0 or (msg.password and crypto.createHash('md5').update(msg.password).digest('hex') is game.password)`

**Comment by jwarwick** [comment]
Exception is no longer relevant since we migrated away from the coffeescript server.
