### ISSUE TITLE
/bug command is broken

### ISSUE THREAD

**Issue by queueseven** [mtgred/netrunner#6622]
Caught an error in the message handler
java.lang.ClassCastException: clojure.lang.PersistentVector incompatible with java.lang.CharSequence
        at clojure.string$trim.invokeStatic(string.clj:234)
        at clojure.string$trim.invoke(string.clj:234)
        at game.core.say$make_message.invokeStatic(say.clj:12)
        at game.core.say$make_message.invoke(say.clj:7)
        at game.core.say$make_system_message.invokeStatic(say.clj:18)
        at game.core.say$make_system_message.invoke(say.clj:15)
        at game.core.say$unsafe_say.invokeStatic(say.clj:37)
        at game.core.say$unsafe_say.invoke(say.clj:34)
        at game.core.commands$command_bug_report.invokeStatic(commands.clj:68)
        at game.core.commands$command_bug_report.invoke(commands.clj:61)
        at game.core.process_actions$command_parser.invokeStatic(process_actions.clj:40)
        at game.core.process_actions$command_parser.invoke(process_actions.clj:34)
        at game.main$handle_say.invokeStatic(main.clj:29)
        at game.main$handle_say.invoke(main.clj:25)

**Comment by queueseven** [comment]
Ah, yes, this is a duplicate of #6585.
