### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by ahshah** [mtgred/netrunner#721]
Not sure if this is the best place to ask for help trying to build the project, but here goes:

$ lein cljsbuild auto dev
Exception in thread "main" java.lang.NoSuchMethodError: clojure.lang.RT.keyword(Ljava/lang/String;Ljava/lang/String;)Lclojure/lang/Keyword; (cljsbuild.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:5441)
	at clojure.lang.Compiler.eval(Compiler.java:5416)
	at clojure.lang.Compiler.load(Compiler.java:5858)
	at clojure.lang.RT.loadResourceScript(RT.java:340)
	at clojure.lang.RT.loadResourceScript(RT.java:331)
	at clojure.lang.RT.load(RT.java:409)
	at clojure.lang.RT.load(RT.java:381)
	at clojure.core$load$fn__4519.invoke(core.clj:4915)
	at clojure.core$load.doInvoke(core.clj:4914)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:4729)
	at clojure.core$load_lib.doInvoke(core.clj:4766)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:542)
	at clojure.core$load_libs.doInvoke(core.clj:4800)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:542)
	at clojure.core$require.doInvoke(core.clj:4881)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at leiningen.core$resolve_task.invoke(core.clj:208)
	at leiningen.core$apply_task.invoke(core.clj:258)
	at leiningen.core$_main.doInvoke(core.clj:329)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invoke(core.clj:542)
	at leiningen.core$_main.invoke(core.clj:332)
	at user$eval73.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.Compiler.eval(Compiler.java:5425)
	at clojure.lang.Compiler.eval(Compiler.java:5392)
	at clojure.core$eval.invoke(core.clj:2382)
	at clojure.main$eval_opt.invoke(main.clj:235)
	at clojure.main$initialize.invoke(main.clj:254)
	at clojure.main$script_opt.invoke(main.clj:270)
	at clojure.main$main.doInvoke(main.clj:354)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at clojure.lang.Var.invoke(Var.java:385)
	at clojure.lang.AFn.applyToHelper(AFn.java:185)
	at clojure.lang.Var.applyTo(Var.java:482)
	at clojure.main.main(main.java:37)
Caused by: java.lang.NoSuchMethodError: clojure.lang.RT.keyword(Ljava/lang/String;Ljava/lang/String;)Lclojure/lang/Keyword;
	at fs.core__init.__init0(Unknown Source)
	at fs.core__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at clojure.lang.RT.loadClassForName(RT.java:1578)
	at clojure.lang.RT.load(RT.java:399)
	at clojure.lang.RT.load(RT.java:381)
	at clojure.core$load$fn__4519.invoke(core.clj:4915)
	at clojure.core$load.doInvoke(core.clj:4914)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:4729)
	at clojure.core$load_lib.doInvoke(core.clj:4766)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:542)
	at clojure.core$load_libs.doInvoke(core.clj:4800)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:542)
	at clojure.core$require.doInvoke(core.clj:4881)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at leiningen.cljsbuild$eval99$loading__4414__auto____100.invoke(cljsbuild.clj:1)
	at leiningen.cljsbuild$eval99.invoke(cljsbuild.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:5425)
	... 37 more

**Comment by JoelCFC25** [comment]
Can you supply some additional details? What OS? Did you get all the preceding steps (i.e., the required software/libraries) completed without error?

**Comment by ahshah** [comment]
I'm trying to build on Ubuntu (Trusty Tahr) 
I was able to complete all preceding steps up till retrieving the cards via:
 $ coffee fetch.coffee

**Comment by JoelCFC25** [comment]
What is the output of: 

`lein version`  and 'java -version` ?

**Comment by ahshah** [comment]
$ ~/ws/app_generator/runt $ lein version
Leiningen 1.7.1 on Java 1.7.0_79 OpenJDK 64-Bit Server VM
$ ~/ws/app_generator/runt $ java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.04.2)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
$ ~/ws/app_generator/runt

**Comment by ahshah** [comment]
$ lein version
Leiningen 1.7.1 on Java 1.7.0_79 OpenJDK 64-Bit Server VM
$ java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.04.2)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

**Comment by JoelCFC25** [comment]
I'm fairly certain you need Leinengen 2 and Java 8. On my MacBook, `lein version` returns: 

`Leiningen 2.5.1 on Java 1.8.0_45 Java HotSpot(TM) 64-Bit Server VM`

**Comment by ahshah** [comment]
I'm giving it a shot now, it seems much happier, if it succeeds, I'll close this issue.

**Comment by JoelCFC25** [comment]
Also see https://github.com/mtgred/netrunner/wiki/Getting-Started-with-Development

**Comment by ahshah** [comment]
Thanks for the URLs.
Does the:
$ lein cljsbuild auto dev 
Take some time to complete? Its just sitting there, not consuming a terrible amount of CPU cycles.

**Comment by JoelCFC25** [comment]
Doesn't usually take more than 10 or 15 seconds, but for me it never exits cleanly back to the prompt and I have to Ctrl-C when it's done.

```Joel:[~/netrunner] $: lein cljsbuild auto dev
Compiling ClojureScript.
Compiling "resources/public/cljs/app.js" from ["src/cljs"]...
Successfully compiled "resources/public/cljs/app.js" in 4.933 seconds.```

**Comment by ahshah** [comment]
Ditto here.

**Comment by ahshah** [comment]
Now I'm stuck here:

$ stylus -w src/css -o resources/public/css/
  watching /usr/lib/node_modules/stylus/lib/functions/index.styl
  watching src/css/fonts.styl
  watching src/css/variables.styl
  watching src/css/mixins.styl
  watching src/css/base.styl
  compiled resources/public/css/mixins.css
  compiled resources/public/css/variables.css
  compiled resources/public/css/base.css
  compiled resources/public/css/fonts.css
  compiled resources/public/css/netrunner.css
  watching src/css/netrunner.styl

**Comment by JoelCFC25** [comment]
You don't need to be doing that part unless you will be changing CSS (unlikely). Can you just background the process? Or just continue in another shell.

**Comment by ahshah** [comment]
Ok, did that.
Now problems running the coffee server:

$ coffee server.coffee 
Error: Could not locate the bindings file. Tried:
 → /home/hyshah/netrunner/node_modules/zmq/build/zmq.node
 → /home/hyshah/netrunner/node_modules/zmq/build/Debug/zmq.node
 → /home/hyshah/netrunner/node_modules/zmq/build/Release/zmq.node
 → /home/hyshah/netrunner/node_modules/zmq/out/Debug/zmq.node
 → /home/hyshah/netrunner/node_modules/zmq/Debug/zmq.node
 → /home/hyshah/netrunner/node_modules/zmq/out/Release/zmq.node
 → /home/hyshah/netrunner/node_modules/zmq/Release/zmq.node
 → /home/hyshah/netrunner/node_modules/zmq/build/default/zmq.node
 → /home/hyshah/netrunner/node_modules/zmq/compiled/0.10.25/linux/x64/zmq.node
    at bindings (/home/hyshah/netrunner/node_modules/zmq/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/hyshah/netrunner/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/hyshah/netrunner/node_modules/zmq/index.js:2:18)
    at Module._compile (module.js:456:26)

**Comment by queueseven** [comment]
It's totally normal that `lein cljsbuild auto dev` runs forever. When you provide the `auto` argument, it means it will run forever and watch your cljs files. If they change, it will automatically compile them.

Same for the `stylus` command. It will watch the css files and automatically rebuild them when they change.

You have to install the ZMQ modules manually. I think I had the same issues on Linux and Windows(?) and it's a known issue IIRC. Just google "Node.js ZMQ" or something like that and you should find a solution. Sorry for short answer but I'm currently on mobile.

**Comment by queueseven** [comment]
Maybe it's just `npm install zmq`, don't remember exactly

**Comment by queueseven** [comment]
Maybe that you also need the ` zeromq-devel` package before running `npm` or something like that

**Comment by ahshah** [comment]
Sweet, i did the following:
$ sudo apt-get install libzmq-dev 
$ npm install zmq 
Not sure if i needed the libzmq-dev, but  everything seems to be working now :). I'm going to close the issue.

**Comment by queueseven** [comment]
If you want to contribute regulary, we could invite you to our Slack site (OK, mtgred could invite you :-). Just drop him a mail.
